In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from openpyxl import Workbook
from openpyxl import load_workbook

In [2]:
TODAY = "2021-04-13"
TODAY_DATE = f"{TODAY} 00:00:00.csv"
HEADINGS = ["HH", "HL", "HHL", "LH", "LL", "LHL"]

In [9]:
workbook = load_workbook(filename="../data/sheets/daily_high_lows.xlsx")
sheet = workbook.active

In [4]:
EXCEL_MAPPING = {
    "HH_STOCKS" : "B17:B26",
    "HH_VALUES" : "C17:C26",
    
    "HL_STOCKS" : "E17:E26",
    "HL_VALUES" : "F17:F26",

    "HHL_STOCKS" : "H17:H26",
    "HHL_VALUES" : "I17:I26",

    "LH_STOCKS" : "B31:B40",
    "LH_VALUES" : "C31:C40",

    "LL_STOCKS" : "E31:E40",
    "LL_VALUES" : "F31:F40",

    "LHL_STOCKS" : "H31:H40",
    "LHL_VALUES" : "I31:I40"
}


NEGATE_EXCEL_MAPPING = {
    "HH_STOCKS" : "K17:K26",
    "HH_VALUES" : "L17:L26",
    
    "HL_STOCKS" : "N17:N26",
    "HL_VALUES" : "O17:O26",

    "HHL_STOCKS" : "Q17:Q26",
    "HHL_VALUES" : "R17:R26",

    "LH_STOCKS" : "K31:K40",
    "LH_VALUES" : "L31:L40",

    "LL_STOCKS" : "N31:N40",
    "LL_VALUES" : "O31:O40",

    "LHL_STOCKS" : "Q31:Q40",
    "LHL_VALUES" : "R31:R40"
}

In [5]:
def write_to_excel(HEADING, EXCEL_MAPPING, data_df):

    temp_data_df = data_df[['NAME',HEADING,'CLOSE']].sort_values([HEADING,'CLOSE'], ascending=False).head(10)
    print(temp_data_df)

    excel_data = temp_data_df[['NAME', HEADING]].values
    print(excel_data)
    try:
        for index,i in enumerate(sheet[EXCEL_MAPPING[f"{HEADING}_STOCKS"]]):
            i[0].value = excel_data[index][0]
    except:
        print("LESS THAN 10 VALUES")
        

    try:
        for index,i in enumerate(sheet[EXCEL_MAPPING[f"{HEADING}_VALUES"]]):
            i[0].value = excel_data[index][1]
        
    except :
        print("LESS THAN 10 VALUES")
        
    return True

In [6]:
data_df = pd.read_csv(f"../data/daily/{TODAY_DATE}")
for h in HEADINGS:
    write_to_excel(h, EXCEL_MAPPING, data_df)

           NAME  HH     CLOSE
62      DRREDDY   6   4777.30
90   HINDUNILVR   5   2454.40
150      PFIZER   3   5081.95
151        PGHH   2  13540.70
191         VBL   2   1004.55
117  LAURUSLABS   2    439.80
134         MRF   1  82671.60
146     PAGEIND   1  29260.75
22   BAJAJFINSV   1   9806.70
127      MARUTI   1   6815.80
[['DRREDDY' 6]
 ['HINDUNILVR' 5]
 ['PFIZER' 3]
 ['PGHH' 2]
 ['VBL' 2]
 ['LAURUSLABS' 2]
 ['MRF' 1]
 ['PAGEIND' 1]
 ['BAJAJFINSV' 1]
 ['MARUTI' 1]]
           NAME  HL     CLOSE
62      DRREDDY   6   4777.30
90   HINDUNILVR   6   2454.40
106     IPCALAB   6   2159.05
137  NATCOPHARM   5    913.25
10        ALKEM   3   2751.75
150      PFIZER   2   5081.95
171   SUNPHARMA   2    627.35
134         MRF   1  82671.60
167    SHREECEM   1  30356.05
146     PAGEIND   1  29260.75
[['DRREDDY' 6]
 ['HINDUNILVR' 6]
 ['IPCALAB' 6]
 ['NATCOPHARM' 5]
 ['ALKEM' 3]
 ['PFIZER' 2]
 ['SUNPHARMA' 2]
 ['MRF' 1]
 ['SHREECEM' 1]
 ['PAGEIND' 1]]
           NAME  HHL     CLOSE
62      DRREDDY    6   4777.30
90   HINDUNILVR    5   2454.40
150      PFIZER    2   5081.95
134         MRF    1  82671.60
146     PAGEIND    1  29260.75
151        PGHH    1  13540.70
22   BAJAJFINSV    1   9806.70
169         SRF    1   6052.80
24   BAJFINANCE    1   4728.75
138      NAUKRI    1   4556.85
[['DRREDDY' 6]
 ['HINDUNILVR' 5]
 ['PFIZER' 2]
 ['MRF' 1]
 ['PAGEIND' 1]
 ['PGHH' 1]
 ['BAJAJFINSV' 1]
 ['SRF' 1]
 ['BAJFINANCE' 1]
 ['NAUKRI' 1]]
           NAME  LH    CLOSE
124      M&MFIN   7   176.70
11   AMARAJABAT   6   805.15
186    TVSMOTOR   6   547.95
8    ADANITRANS   5   899.25
31          BEL   5   125.60
142        NTPC   5   100.60
161    RELIANCE   4  1931.80
53   CUMMINSIND   4   839.65
7    ADANIPORTS   4   731.05
190         UPL   4   604.60
[['M&MFIN' 7]
 ['AMARAJABAT' 6]
 ['TVSMOTOR' 6]
 ['ADANITRANS' 5]
 ['BEL' 5]
 ['NTPC' 5]
 ['RELIANCE' 4]
 ['CUMMINSIND' 4]
 ['ADANIPORTS' 4]
 ['UPL' 4]]
           NAME  LL     CLOSE
6    ADANIGREEN   5   1116.05
8    ADANITRANS   5    899.25
69       FORTIS   4    200.90
92   IBULHSGFIN   4    171.85
37     BOSCHLTD   3  13887.95
127      MARUTI   3   6815.80
56    DEEPAKNTR   3   1587.10
65    ENDURANCE   3   1298.80
164     SBICARD   3    898.00
53   CUMMINSIND   3    839.65
[['ADANIGREEN' 5]
 ['ADANITRANS' 5]
 ['FORTIS' 4]
 ['IBULHSGFIN' 4]
 ['BOSCHLTD' 3]
 ['MARUTI' 3]
 ['DEEPAKNTR' 3]
 ['ENDURANCE' 3]
 ['SBICARD' 3]
 ['CUMMINSIND' 3]]
           NAME  LHL     CLOSE
8    ADANITRANS    5    899.25
92   IBULHSGFIN    4    171.85
37     BOSCHLTD    3  13887.95
56    DEEPAKNTR    3   1587.10
65    ENDURANCE    3   1298.80
53   CUMMINSIND    3    839.65
174    TATACHEM    3    759.15
184  TORNTPOWER    3    397.00
3         ABFRL    3    176.50
197     YESBANK    3     14.70
[['ADANITRANS' 5]
 ['IBULHSGFIN' 4]
 ['BOSCHLTD' 3]
 ['DEEPAKNTR' 3]
 ['ENDURANCE' 3]
 ['CUMMINSIND' 3]
 ['TATACHEM' 3]
 ['TORNTPOWER' 3]
 ['ABFRL' 3]
 ['YESBANK' 3]]

In [7]:
for h in HEADINGS:
    data_file = pd.read_csv(f"../data/negate/daily/{h}.csv")
    write_to_excel(h, NEGATE_EXCEL_MAPPING, data_file)

         NAME  HH    CLOSE
0  LALPATHLAB  10  3336.55
1   BRITANNIA   9  3812.75
2    GLENMARK   9   497.95
3        INFY   7  1425.75
4    CADILAHC   6   499.70
5    MINDTREE   5  2142.50
6       LUPIN   5  1045.15
7      SANOFI   4  8094.20
8      APLLTD   4   960.45
9  NATCOPHARM   4   917.95
[['LALPATHLAB' 10]
 ['BRITANNIA' 9]
 ['GLENMARK' 9]
 ['INFY' 7]
 ['CADILAHC' 6]
 ['MINDTREE' 5]
 ['LUPIN' 5]
 ['SANOFI' 4]
 ['APLLTD' 4]
 ['NATCOPHARM' 4]]
       NAME  HL   CLOSE
0     DHANI   6  211.35
1  CADILAHC   5  499.70
[['DHANI' 6]
 ['CADILAHC' 5]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
       NAME  HHL    CLOSE
0  CADILAHC    5   499.70
1     TECHM    3  1039.85
2     CIPLA    1   902.40
[['CADILAHC' 5]
 ['TECHM' 3]
 ['CIPLA' 1]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
        NAME  LH   CLOSE
0  POWERGRID   4  201.15
[['POWERGRID' 4]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
       NAME  LL   CLOSE
0  TVSMOTOR   6  538.90
1      NTPC   4   99.05
[['TVSMOTOR' 6]
 ['NTPC' 4]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
         NAME  LHL     CLOSE
0   POWERGRID    3    201.15
1         MRF    2  79227.85
2     PAGEIND    2  28195.60
3  BAJAJFINSV    2   9163.15
4  BAJFINANCE    2   4511.00
5  BAJAJ-AUTO    2   3541.00
6  ASIANPAINT    2   2602.20
7   KOTAKBANK    2   1742.50
8  BALKRISIND    2   1606.20
9    HDFCBANK    2   1367.05
[['POWERGRID' 3]
 ['MRF' 2]
 ['PAGEIND' 2]
 ['BAJAJFINSV' 2]
 ['BAJFINANCE' 2]
 ['BAJAJ-AUTO' 2]
 ['ASIANPAINT' 2]
 ['KOTAKBANK' 2]
 ['BALKRISIND' 2]
 ['HDFCBANK' 2]]

In [11]:
workbook.save(filename=f"../data/sheets/{TODAY}_high_lows.xlsx")