In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from openpyxl import Workbook
from openpyxl import load_workbook

In [2]:
TODAY = "2021-04-29"
TODAY_DATE = f"{TODAY} 00:00:00.csv"
HEADINGS = ["HH", "HL", "HHL", "LH", "LL", "LHL"]

In [3]:
workbook = load_workbook(filename="../data/output/sheets/daily_high_lows.xlsx")
sheet = workbook.active

In [4]:
EXCEL_MAPPING = {
    "HH_STOCKS" : "B17:B26",
    "HH_VALUES" : "C17:C26",
    
    "HL_STOCKS" : "E17:E26",
    "HL_VALUES" : "F17:F26",

    "HHL_STOCKS" : "H17:H26",
    "HHL_VALUES" : "I17:I26",

    "LH_STOCKS" : "B31:B40",
    "LH_VALUES" : "C31:C40",

    "LL_STOCKS" : "E31:E40",
    "LL_VALUES" : "F31:F40",

    "LHL_STOCKS" : "H31:H40",
    "LHL_VALUES" : "I31:I40"
}


NEGATE_EXCEL_MAPPING = {
    "HH_STOCKS" : "K17:K26",
    "HH_VALUES" : "L17:L26",
    
    "HL_STOCKS" : "N17:N26",
    "HL_VALUES" : "O17:O26",

    "HHL_STOCKS" : "Q17:Q26",
    "HHL_VALUES" : "R17:R26",

    "LH_STOCKS" : "K31:K40",
    "LH_VALUES" : "L31:L40",

    "LL_STOCKS" : "N31:N40",
    "LL_VALUES" : "O31:O40",

    "LHL_STOCKS" : "Q31:Q40",
    "LHL_VALUES" : "R31:R40"
}

In [5]:
def write_to_excel(HEADING, EXCEL_MAPPING, data_df):

    temp_data_df = data_df[['NAME',HEADING,'CLOSE']].sort_values([HEADING,'CLOSE'], ascending=False).head(10)
    print(temp_data_df)

    excel_data = temp_data_df[['NAME', HEADING]].values
    print(excel_data)
    try:
        for index,i in enumerate(sheet[EXCEL_MAPPING[f"{HEADING}_STOCKS"]]):
            i[0].value = excel_data[index][0]
    except:
        print("LESS THAN 10 VALUES")
        

    try:
        for index,i in enumerate(sheet[EXCEL_MAPPING[f"{HEADING}_VALUES"]]):
            i[0].value = excel_data[index][1]
        
    except :
        print("LESS THAN 10 VALUES")
        
    return True

In [6]:
data_df = pd.read_csv(f"../data/output/daily/{str(TODAY_DATE)[:10]}.csv")
for h in HEADINGS:
    write_to_excel(h, EXCEL_MAPPING, data_df)

           NAME  HH    CLOSE
187         UBL   8  1196.70
24   BAJFINANCE   7  5484.85
21   BAJAJ-AUTO   7  3836.45
179   TATASTEEL   7  1031.35
112    JSWSTEEL   7   726.50
141        NMDC   7   154.00
162        SAIL   7   112.50
73   GODREJAGRO   6   498.50
169         SRF   5  6440.20
17   ASIANPAINT   5  2613.45
[['UBL' 8]
 ['BAJFINANCE' 7]
 ['BAJAJ-AUTO' 7]
 ['TATASTEEL' 7]
 ['JSWSTEEL' 7]
 ['NMDC' 7]
 ['SAIL' 7]
 ['GODREJAGRO' 6]
 ['SRF' 5]
 ['ASIANPAINT' 5]]
           NAME  HL     CLOSE
196       WIPRO  10    489.85
22   BAJAJFINSV   7  11176.55
100   INDIAMART   7   8815.40
169         SRF   7   6440.20
21   BAJAJ-AUTO   7   3836.45
155     POLYCAB   7   1539.50
179   TATASTEEL   7   1031.35
141        NMDC   7    154.00
162        SAIL   7    112.50
192        VEDL   6    255.05
[['WIPRO' 10]
 ['BAJAJFINSV' 7]
 ['INDIAMART' 7]
 ['SRF' 7]
 ['BAJAJ-AUTO' 7]
 ['POLYCAB' 7]
 ['TATASTEEL' 7]
 ['NMDC' 7]
 ['SAIL' 7]
 ['VEDL' 6]]
           NAME  HHL    CLOSE
21   BAJAJ-AUTO    7  3836.45
179   TATASTEEL    7  1031.35
141        NMDC    7   154.00
162        SAIL    7   112.50
169         SRF    5  6440.20
24   BAJFINANCE    5  5484.85
63    EICHERMOT    5  2462.90
161    RELIANCE    5  2024.05
152  PIDILITIND    5  1848.20
25   BALKRISIND    5  1766.85
[['BAJAJ-AUTO' 7]
 ['TATASTEEL' 7]
 ['NMDC' 7]
 ['SAIL' 7]
 ['SRF' 5]
 ['BAJFINANCE' 5]
 ['EICHERMOT' 5]
 ['RELIANCE' 5]
 ['PIDILITIND' 5]
 ['BALKRISIND' 5]]
           NAME  LH     CLOSE
48       COLPAL   8   1485.80
45        CIPLA   6    906.50
39    BRITANNIA   5   3468.90
183  TORNTPHARM   5   2500.45
82      HCLTECH   4    909.55
89    HINDPETRO   4    229.70
127      MARUTI   3   6565.65
120         LTI   3   3851.00
95   ICICIPRULI   3    524.50
140   NESTLEIND   2  16502.55
[['COLPAL' 8]
 ['CIPLA' 6]
 ['BRITANNIA' 5]
 ['TORNTPHARM' 5]
 ['HCLTECH' 4]
 ['HINDPETRO' 4]
 ['MARUTI' 3]
 ['LTI' 3]
 ['ICICIPRULI' 3]
 ['NESTLEIND' 2]]
           NAME  LL     CLOSE
39    BRITANNIA   5   3468.90
36       BIOCON   5    393.90
48       COLPAL   4   1485.80
13       APLLTD   3    982.10
57        DHANI   3    179.55
140   NESTLEIND   2  16502.55
120         LTI   2   3851.00
5      ADANIENT   2   1182.30
82      HCLTECH   2    909.55
137  NATCOPHARM   2    890.15
[['BRITANNIA' 5]
 ['BIOCON' 5]
 ['COLPAL' 4]
 ['APLLTD' 3]
 ['DHANI' 3]
 ['NESTLEIND' 2]
 ['LTI' 2]
 ['ADANIENT' 2]
 ['HCLTECH' 2]
 ['NATCOPHARM' 2]]
          NAME  LHL     CLOSE
39   BRITANNIA    5   3468.90
48      COLPAL    4   1485.80
140  NESTLEIND    2  16502.55
120        LTI    2   3851.00
13      APLLTD    2    982.10
82     HCLTECH    2    909.55
89   HINDPETRO    2    229.70
57       DHANI    2    179.55
134        MRF    1  77656.90
146    PAGEIND    1  29890.70
[['BRITANNIA' 5]
 ['COLPAL' 4]
 ['NESTLEIND' 2]
 ['LTI' 2]
 ['APLLTD' 2]
 ['HCLTECH' 2]
 ['HINDPETRO' 2]
 ['DHANI' 2]
 ['MRF' 1]
 ['PAGEIND' 1]]

In [7]:
for h in HEADINGS:
    data_file = pd.read_csv(f"../data/output/negate/daily/{h}.csv")
    write_to_excel(h, NEGATE_EXCEL_MAPPING, data_file)

         NAME  HH    CLOSE
0      NAUKRI   8  5020.85
1  NAVINFLUOR   6  3350.80
2  CUMMINSIND   5   882.50
3    DIVISLAB   4  3882.60
4    AARTIIND   4  1539.20
5   BATAINDIA   4  1348.95
6    ADANIENT   4  1185.20
7        MFSL   4   919.50
8    TVSMOTOR   4   645.80
9   NAM-INDIA   4   341.40
[['NAUKRI' 8]
 ['NAVINFLUOR' 6]
 ['CUMMINSIND' 5]
 ['DIVISLAB' 4]
 ['AARTIIND' 4]
 ['BATAINDIA' 4]
 ['ADANIENT' 4]
 ['MFSL' 4]
 ['TVSMOTOR' 4]
 ['NAM-INDIA' 4]]
         NAME  HL     CLOSE
0  ABBOTINDIA   6  15172.90
1      NAUKRI   6   5020.85
2     ICICIGI   6   1424.90
3  CUMMINSIND   6    882.50
4    HINDZINC   6    308.20
5  IBULHSGFIN   6    186.80
6       ABFRL   6    179.75
7  HEROMOTOCO   4   2926.25
8  ASIANPAINT   4   2614.55
9    AARTIIND   4   1539.20
[['ABBOTINDIA' 6]
 ['NAUKRI' 6]
 ['ICICIGI' 6]
 ['CUMMINSIND' 6]
 ['HINDZINC' 6]
 ['IBULHSGFIN' 6]
 ['ABFRL' 6]
 ['HEROMOTOCO' 4]
 ['ASIANPAINT' 4]
 ['AARTIIND' 4]]
         NAME  HHL     CLOSE
0      NAUKRI    6   5020.85
1  CUMMINSIND    5    882.50
2    AARTIIND    4   1539.20
3   BATAINDIA    4   1348.95
4    INDHOTEL    4    113.65
5     PAGEIND    3  30034.30
6    DIVISLAB    3   3882.60
7  HEROMOTOCO    3   2926.25
8  IBULHSGFIN    3    186.80
9       ABFRL    3    179.75
[['NAUKRI' 6]
 ['CUMMINSIND' 5]
 ['AARTIIND' 4]
 ['BATAINDIA' 4]
 ['INDHOTEL' 4]
 ['PAGEIND' 3]
 ['DIVISLAB' 3]
 ['HEROMOTOCO' 3]
 ['IBULHSGFIN' 3]
 ['ABFRL' 3]]
         NAME  LH    CLOSE
0      PFIZER   4  5142.75
1     DRREDDY   4  5044.45
2       ALKEM   4  2774.75
3  AUROPHARMA   4   963.00
[['PFIZER' 4]
 ['DRREDDY' 4]
 ['ALKEM' 4]
 ['AUROPHARMA' 4]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
Empty DataFrame
Columns: [NAME, LL, CLOSE]
Index: []
[]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
         NAME  LHL    CLOSE
0  AUROPHARMA    3   963.00
1     HDFCAMC    1  2806.00
2     SBILIFE    1   930.40
3        CESC    1   611.25
4        ISEC    1   465.80
5  JINDALSTEL    1   443.60
[['AUROPHARMA' 3]
 ['HDFCAMC' 1]
 ['SBILIFE' 1]
 ['CESC' 1]
 ['ISEC' 1]
 ['JINDALSTEL' 1]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES

In [8]:
workbook.save(filename=f"../data/output/sheets/{str(TODAY)[:10]}_high_lows.xlsx")