In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from openpyxl import Workbook
from openpyxl import load_workbook

In [2]:
TODAY = "2021-04-16"
TODAY_DATE = f"{TODAY} 00:00:00.csv"
HEADINGS = ["HH", "HL", "HHL", "LH", "LL", "LHL"]

In [3]:
workbook = load_workbook(filename="../data/output/sheets/daily_high_lows.xlsx")
sheet = workbook.active

In [4]:
EXCEL_MAPPING = {
    "HH_STOCKS" : "B17:B26",
    "HH_VALUES" : "C17:C26",
    
    "HL_STOCKS" : "E17:E26",
    "HL_VALUES" : "F17:F26",

    "HHL_STOCKS" : "H17:H26",
    "HHL_VALUES" : "I17:I26",

    "LH_STOCKS" : "B31:B40",
    "LH_VALUES" : "C31:C40",

    "LL_STOCKS" : "E31:E40",
    "LL_VALUES" : "F31:F40",

    "LHL_STOCKS" : "H31:H40",
    "LHL_VALUES" : "I31:I40"
}


NEGATE_EXCEL_MAPPING = {
    "HH_STOCKS" : "K17:K26",
    "HH_VALUES" : "L17:L26",
    
    "HL_STOCKS" : "N17:N26",
    "HL_VALUES" : "O17:O26",

    "HHL_STOCKS" : "Q17:Q26",
    "HHL_VALUES" : "R17:R26",

    "LH_STOCKS" : "K31:K40",
    "LH_VALUES" : "L31:L40",

    "LL_STOCKS" : "N31:N40",
    "LL_VALUES" : "O31:O40",

    "LHL_STOCKS" : "Q31:Q40",
    "LHL_VALUES" : "R31:R40"
}

In [5]:
def write_to_excel(HEADING, EXCEL_MAPPING, data_df):

    temp_data_df = data_df[['NAME',HEADING,'CLOSE']].sort_values([HEADING,'CLOSE'], ascending=False).head(10)
    print(temp_data_df)

    excel_data = temp_data_df[['NAME', HEADING]].values
    print(excel_data)
    try:
        for index,i in enumerate(sheet[EXCEL_MAPPING[f"{HEADING}_STOCKS"]]):
            i[0].value = excel_data[index][0]
    except:
        print("LESS THAN 10 VALUES")
        

    try:
        for index,i in enumerate(sheet[EXCEL_MAPPING[f"{HEADING}_VALUES"]]):
            i[0].value = excel_data[index][1]
        
    except :
        print("LESS THAN 10 VALUES")
        
    return True

In [6]:
data_df = pd.read_csv(f"../data/output/weekly/{str(TODAY_DATE)[:10]}.csv")
for h in HEADINGS:
    write_to_excel(h, EXCEL_MAPPING, data_df)

           NAME  HH    CLOSE
90   HINDUNILVR   7  2458.90
131    MINDTREE   7  2069.65
62   LALPATHLAB   6  2920.20
18   ASIANPAINT   6  2663.70
112    JSWSTEEL   5   619.40
60     DIVISLAB   4  3821.85
40    BRITANNIA   4  3696.50
182  TORNTPHARM   4  2619.50
11       APLLTD   4  1001.20
19   AUROPHARMA   4   953.00
[['HINDUNILVR' 7]
 ['MINDTREE' 7]
 ['LALPATHLAB' 6]
 ['ASIANPAINT' 6]
 ['JSWSTEEL' 5]
 ['DIVISLAB' 4]
 ['BRITANNIA' 4]
 ['TORNTPHARM' 4]
 ['APLLTD' 4]
 ['AUROPHARMA' 4]]
           NAME  HL     CLOSE
112    JSWSTEEL   8    619.40
62   LALPATHLAB   7   2920.20
90   HINDUNILVR   7   2458.90
139   NESTLEIND   4  17252.10
161         SRF   4   6127.25
147      PFIZER   4   5218.55
63      DRREDDY   4   4893.25
60     DIVISLAB   4   3821.85
40    BRITANNIA   4   3696.50
138  NAVINFLUOR   4   3135.50
[['JSWSTEEL' 8]
 ['LALPATHLAB' 7]
 ['HINDUNILVR' 7]
 ['NESTLEIND' 4]
 ['SRF' 4]
 ['PFIZER' 4]
 ['DRREDDY' 4]
 ['DIVISLAB' 4]
 ['BRITANNIA' 4]
 ['NAVINFLUOR' 4]]
           NAME  HHL    CLOSE
90   HINDUNILVR    7  2458.90
62   LALPATHLAB    6  2920.20
112    JSWSTEEL    5   619.40
60     DIVISLAB    4  3821.85
40    BRITANNIA    4  3696.50
182  TORNTPHARM    4  2619.50
11       APLLTD    4  1001.20
19   AUROPHARMA    4   953.00
121  LAURUSLABS    4   446.50
162      SANOFI    3  8047.70
[['HINDUNILVR' 7]
 ['LALPATHLAB' 6]
 ['JSWSTEEL' 5]
 ['DIVISLAB' 4]
 ['BRITANNIA' 4]
 ['TORNTPHARM' 4]
 ['APLLTD' 4]
 ['AUROPHARMA' 4]
 ['LAURUSLABS' 4]
 ['SANOFI' 3]]
           NAME  LH    CLOSE
195   WHIRLPOOL  10  2138.25
193        IDEA   9     8.85
166        SBIN   8   339.90
106  INDUSINDBK   7   862.95
48    COALINDIA   7   127.85
86   HEROMOTOCO   6  2894.85
77   GODREJPROP   6  1336.90
30    BATAINDIA   6  1323.55
159     SBICARD   6   973.70
88          HAL   6   964.50
[['WHIRLPOOL' 10]
 ['IDEA' 9]
 ['SBIN' 8]
 ['INDUSINDBK' 7]
 ['COALINDIA' 7]
 ['HEROMOTOCO' 6]
 ['GODREJPROP' 6]
 ['BATAINDIA' 6]
 ['SBICARD' 6]
 ['HAL' 6]]
           NAME  LL    CLOSE
102         IOC   6    90.15
129      MARUTI   5  6648.10
86   HEROMOTOCO   5  2894.85
115   KOTAKBANK   5  1764.10
149         PEL   5  1720.05
30    BATAINDIA   5  1323.55
126         M&M   5   821.65
184       TRENT   5   743.65
99   IBULHSGFIN   5   165.80
151         PFC   5   109.10
[['IOC' 6]
 ['MARUTI' 5]
 ['HEROMOTOCO' 5]
 ['KOTAKBANK' 5]
 ['PEL' 5]
 ['BATAINDIA' 5]
 ['M&M' 5]
 ['TRENT' 5]
 ['IBULHSGFIN' 5]
 ['PFC' 5]]
           NAME  LHL    CLOSE
129      MARUTI    5  6648.10
86   HEROMOTOCO    5  2894.85
30    BATAINDIA    5  1323.55
99   IBULHSGFIN    5   165.80
149         PEL    3  1720.05
97   IDFCFIRSTB    3    53.65
23   BAJFINANCE    2  4616.60
22   BAJAJ-AUTO    2  3634.65
114    JUBLFOOD    2  2820.65
64    EICHERMOT    2  2434.85
[['MARUTI' 5]
 ['HEROMOTOCO' 5]
 ['BATAINDIA' 5]
 ['IBULHSGFIN' 5]
 ['PEL' 3]
 ['IDFCFIRSTB' 3]
 ['BAJFINANCE' 2]
 ['BAJAJ-AUTO' 2]
 ['JUBLFOOD' 2]
 ['EICHERMOT' 2]]

In [7]:
for h in HEADINGS:
    data_file = pd.read_csv(f"../data/output/negate/weekly/{h}.csv")
    write_to_excel(h, NEGATE_EXCEL_MAPPING, data_file)

Empty DataFrame
Columns: [NAME, HH, CLOSE]
Index: []
[]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
       NAME  HL     CLOSE
0  SHREECEM   4  30356.05
1  RAMCOCEM   4   1056.80
[['SHREECEM' 4]
 ['RAMCOCEM' 4]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
Empty DataFrame
Columns: [NAME, HHL, CLOSE]
Index: []
[]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
        NAME  LH    CLOSE
0      TRENT   6   729.25
1       ONGC   5   102.05
2  DALBHARAT   4  1541.10
[['TRENT' 6]
 ['ONGC' 5]
 ['DALBHARAT' 4]]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
Empty DataFrame
Columns: [NAME, LL, CLOSE]
Index: []
[]
LESS THAN 10 VALUES
LESS THAN 10 VALUES
Empty DataFrame
Columns: [NAME, LHL, CLOSE]
Index: []
[]
LESS THAN 10 VALUES
LESS THAN 10 VALUES

In [8]:
workbook.save(filename=f"../data/output/sheets/{str(TODAY)[:10]}_high_lows_weekly.xlsx")